### ISSUE TITLE
close

### ISSUE THREAD

**Issue by yongheng2016** [yongheng2016/css-icon#1]
```html
<div class="close"></div>
```
```css
.close {
    position: absolute;
    bottom: -8rem;
    left: 50%;
    transform: translate(-50%, -50%) rotate(45deg);
    width: 3.9rem;
    height: 3.9rem;
    border: 1px solid #fff;
    border-radius: 50%;
  }
.close::after,
.close::before {
    content: '';
    display: block;
    position: absolute;
    width: 2.4rem;
    height: 2.4rem;
    top: 50%;
    left: 50%;
    margin-left: -1.2rem;
    border-top: 0.05rem solid #fff;
    position: absolute;
  }
  .close::after {
    transform-origin: 50% 0;
    transform: rotate(-90deg);
  }
```
