### ISSUE TITLE
check_对勾

### ISSUE THREAD

**Issue by yongheng2016** [yongheng2016/css-icon#2]
```html
<div class="checked"></div>
```

```css
  checked::after {
    content: '\00a0';
    display: inline-block;
    position: absolute;
    top: 50%;
    left: 50%;
    border: 4px solid #fff;
    border-top-width: 0;
    border-right-width: 0;
    width: 2.2px;
    height: 1.2px;
    transform: translate(-50%, -50%) rotate(-50deg);
  }
```
