### ISSUE TITLE
>

### ISSUE THREAD

**Issue by yongheng2016** [yongheng2016/css-icon#3]
```
<div></div>
```

```css
  div::after {
    border: solid 1px #c8c8cd;
    border-bottom-width: 0;
    border-left-width: 0;
    content: " ";
    top: 50%;
    right: 2.2rem;
    position: absolute;
    width: 1rem;
    height: 1rem;
    -webkit-transform: translateY(-50%) rotate(45deg);
    transform: translateY(-50%) rotate(45deg);
  }
```
